# ConfigMap
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config
data:
  spring.datasource.url: jdbc:mysql://mysql:3306/livroreceitas
  spring.datasource.hikari.connection-timeout: "5000"
  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.idle-timeout: "10000"
  spring.datasource.hikari.minimum-idle: "2"
  spring.jpa.generate-ddl: 'true'
  spring.jpa.hibernate.ddl-auto: update
  spring.sql.init.mode: always
  spring.sql.init.platform: mysql
  spring.datasource.initialization-mode: always
  spring.datasource.initialize: "true"
#  spring.datasource.data: data.sql